routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

//['verify' => true]

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' =>['auth' , 'auth.admin'] , 'prefix' => 'dashboard'] , function (){
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::resource('advertisement', 'AdvertisementController');
    Route::resource('EstateType', 'EstateTypeController');
    Route::resource('areas', 'AreaController');
});

Route::get('/verify/{token}' , 'HomeController@verify')->name('verify');

Route::get('/lang/{locale}' , function ($locale){
    session()->put('locale' , $locale);
    return redirect()->back()->withInput();
})->name('language');

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    protected $fillable = [
        'name', 'user_id' , 'en' , 'ar',
    ];
    public function user()
    {
        return $this->belongsTo(User::class , 'user_id' , 'id');
    }
}

app/Http/Controllers/Api/AreaController.php
<?php

namespace App\Http\Controllers\Api;

use App\Area;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\Area as AreaResource;

class AreaController extends Controller
{
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required',
        ]);

        Area::create([
            'name' => $validate['name'],
            'user_id' => auth()->user()->id,
            'en' => 'required',
            'ar' => 'required',
        ]);

        return response()->json(['message' => 'Added Successfully'] , 200);
    }


    public function show($locale ,$id)
    {

        \App::setlocale($locale);

        $area = Area::find($id);

        if (\App::getLocale() == 'en'){
            return response()->json(['Lang' => $area->en , 'data' => new AreaResource($area)]);
        }elseif (\App::getLocale() == 'ar'){
            return response()->json(['Lang' => $area->ar , 'data' => new AreaResource($area)]);
        }else{
            return response()->json(['Lang' => 'no language selected']);
        }
    }


    public function update(Request $request, Area $area)
    {
        $validate = $request->validate([
            'name' => 'required',
        ]);

        $area->update([
            'name' => $validate['name'],
            'user_id' => auth()->user()->id,
            'en' => 'required',
            'ar' => 'required',
        ]);


        return response()->json(['message' => 'Updated Successfully'] , 200);

    }


    public function destroy(Area $area)
    {
        $area->delete();

        return response()->json(['message' => 'Deleted Successfully'] , 200);
    }
}

app/Http/Controllers/AreaController.php
<?php

namespace App\Http\Controllers;

use App\Area;
use Illuminate\Http\Request;

class AreaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $areas = Area::paginate(5);

        return view('dashboard.Area.index' , compact('areas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $area = new Area();

        return view('dashboard.Area.create' , compact('area'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validate = $request->validate([
            'name' => 'required',
            'en' => 'required',
            'ar' => 'required',
        ]);

        Area::create([
            'name' => $validate['name'],
            'user_id' => auth()->user()->id,
            'en' => $validate['en'],
            'ar' => $validate['ar'],
        ]);

        return redirect(route('areas.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Area $area)
    {
        return view('dashboard.Area.edit' , compact('area'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Area $area)
    {
        $validate = $request->validate([
            'name' => 'required',
            'en' => 'required',
            'ar' => 'required',
        ]);

        $area->update([
            'name' => $validate['name'],
            'user_id' => auth()->user()->id,
            'en' => $validate['en'],
            'ar' => $validate['at'],
        ]);

        return redirect(route('areas.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Area $area)
    {
        $area->delete();
        return redirect(route('areas.index'));
    }
}

resources/views/dashboard/Area/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="col">
        <form action="{{ route('areas.store') }}" method="POST">

            @include('dashboard.Area.fields');

            <div class="form-group row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary">{{ __('lang.addArea') }}</button>
                </div>
                <div class="col-sm-9">
                    <a href="{{ route('areas.index') }}" class="btn btn-secondary">{{ __('lang.cancel') }}</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/Area/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="col">
        <form action="{{ route('areas.update' , $area) }}" method="POST">
            @method('PUT')

            @include('dashboard.Area.fields');

            <div class="form-group row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary">{{ __('lang.addArea') }}</button>
                </div>
                <div class="col-sm-9">
                    <a href="{{ route('areas.index') }}" class="btn btn-secondary">{{ __('lang.cancel') }}</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/Area/fields.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
        <p class="alert alert-danger">{{ $error }}</p>
    @endforeach
@endif

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="name">{{ __('lang.AreaName') }}</label>
    <div class="col-sm-10">
        <input name="name" type="text" class="form-control" placeholder="Name" value="{{ old('name') ?? $area->name ?? '' }}"/>
        <small class="form-text text-muted">The name of Area</small>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="en">{{ __('lang.EnName') }}</label>
    <div class="col-sm-10">
        <input name="en" type="text" class="form-control" placeholder="Name" value="{{ old('en') ?? $area->en ?? '' }}"/>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="ar">{{ __('lang.ArName') }}</label>
    <div class="col-sm-10">
        <input name="ar" type="text" class="form-control" placeholder="Name" value="{{ old('ar') ?? $area->ar ?? '' }}"/>
    </div>
</div>

@csrf

resources/views/dashboard/Area/index.blade.php
@extends('layouts.dashboard')

@section('buttons')
    <a class="btn btn-primary" href="{{route('areas.create')}}" role="button">{{ __('lang.addNewArea') }}</a>
@endsection

@section('content')
    <table class="table">
        <thead>
        <tr>
            <td>Area ID</td>
            <td>Area Name</td>
            <td>Office Name</td>
            <th class="Actions">{{ __('lang.actions') }}</th>
        </tr>
        </thead>
        <body>
        @foreach($areas as $area)
            <tr>
                <td>{{ $area->id }}</td>
                <td>{{ __('area.' . $area->name) }}</td>
                <td>{{ $area->user->name }}</td>
                <td class="actions">
                    <a
                        href="{{ route('areas.edit', ['area' => $area->id]) }}"
                        alt="Edit"
                        title="Edit">
                        {{ __('lang.edit') }}
                    </a>
                    <form action="{{ route('areas.destroy', ['area' => $area->id]) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-link" title="Delete" value="Delete">{{ __('lang.delete') }}</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </body>
    </table>
    {{ $areas->links() }}
@endsection