routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

//['verify' => true]

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' =>['auth' , 'auth.admin'] , 'prefix' => 'dashboard'] , function (){
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::resource('advertisement', 'AdvertisementController');
    Route::resource('EstateType', 'EstateTypeController');
    Route::resource('areas', 'AreaController');
});

Route::get('/verify/{token}' , 'HomeController@verify')->name('verify');

Route::get('/lang/{locale}' , function ($locale){
    session()->put('locale' , $locale);
    return redirect()->back()->withInput();
})->name('language');

app/Advertisement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Advertisement extends Model
{
    protected $fillable = [
        'name' , 'estate_id', 'en' , 'ar',
    ];

    public function estate()
    {
        return $this->belongsTo(Estates::class , 'estate_id' , 'id');
    }
}

app/Http/Controllers/AdvertisementController.php
<?php

namespace App\Http\Controllers;

use App\Advertisement;
use App\Estates;
use Illuminate\Http\Request;

class AdvertisementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $advertisements = Advertisement::paginate(5);

        return view('dashboard.Advertisement.index' , compact('advertisements'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $estates = Estates::all()->pluck('name' , 'id')->prepend('none');
        $advertisement = new Advertisement();

        return view('dashboard.Advertisement.create' , compact('estates' , 'advertisement'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'estate_id' => 'required|exists:estates,id',
            'name' => 'required',
            'en' => 'required',
            'ar' => 'required',
        ]);

        Advertisement::create($validate);

        return redirect(route('advertisement.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Advertisement $advertisement)
    {
        $estates = Estates::all()->pluck('name' , 'id')->prepend('none');

        return view('dashboard.Advertisement.edit' , compact('advertisement' , 'estates'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Advertisement $advertisement)
    {

        $validate = $request->validate([
            'estate_id' => 'required|exists:estates,id',
            'name' => 'required',
            'en' => 'required',
            'ar' => 'required'
        ]);

        $advertisement->update($validate);

        return redirect(route('advertisement.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Advertisement $advertisement)
    {
        $advertisement->delete();
        return redirect(route('advertisement.index'));
    }
}

app/Http/Controllers/Api/AdvertisementController.php
<?php

namespace App\Http\Controllers\Api;

use App\Advertisement;
use App\Estates;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\Advertisement as AdvertisementResource;

class AdvertisementController extends Controller
{

    public function store(Request $request)
    {
        $validate = $request->validate([
            'estate_id' => 'required|exists:estates,id',
            'name' => 'required',
            'en' => 'required',
            'ar' => 'required',
        ]);

        Advertisement::create($validate);

        return response()->json(['message' => 'Added Successfully'] , 200);
    }


    public function show($locale ,$id)
    {
        \App::setlocale($locale);

        $advertisement = Advertisement::find($id);

        if (\App::getLocale() == 'en'){
            return response()->json(['Lang' => $advertisement->en , 'data' => new AdvertisementResource($advertisement)]);
        }elseif (\App::getLocale() == 'ar'){
            return response()->json(['Lang' => $advertisement->ar , 'data' => new AdvertisementResource($advertisement)]);
        }else{
            return response()->json(['Lang' => 'no language selected']);
        }

    }


    public function update(Request $request, Advertisement $advertisement)
    {
        $validate = $request->validate([
            'estate_id' => 'required|exists:estates,id',
            'name' => 'required',
            'en' => 'required',
            'ar' => 'required',
        ]);

        $advertisement->update($validate);

        return response()->json(['message' => 'Updated Successfully'] , 200);

    }


    public function destroy(Advertisement $advertisement)
    {
        $advertisement->delete();

        return response()->json(['message' => 'Deleted Successfully'] , 200);
    }
}

resources/views/dashboard/Advertisement/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="col">
        <form action="{{ route('advertisement.store') }}" method="POST">

            @include('dashboard.Advertisement.fields');

            <div class="form-group row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary">{{ __('lang.addAdvertisement') }}</button>
                </div>
                <div class="col-sm-9">
                    <a href="{{ route('advertisement.index') }}" class="btn btn-secondary">{{ __('lang.cancel') }}</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/Advertisement/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="col">
        <form action="{{ route('advertisement.update' , $advertisement) }}" method="POST">
            @method('PUT')

            @include('dashboard.Advertisement.fields');

            <div class="form-group row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary">{{ __('lang.addAdvertisement') }}</button>
                </div>
                <div class="col-sm-9">
                    <a href="{{ route('advertisement.index') }}" class="btn btn-secondary">{{ __('lang.cancel') }}</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/Advertisement/fields.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
        <p class="alert alert-danger">{{ $error }}</p>
    @endforeach
@endif

<div class="form-group row">
    <label class="col-sm-2 col-form-label"for="estate_id">{{ __('lang.estateName') }}</label>
    <div class="col-sm-10">
        <select name="estate_id" class="form-control" id="estate_id" required>
            @foreach($estates as $id => $display)
                <option value="{{ $id }}" {{ (isset($advertisement->estate_id) && $id === $advertisement->estate_id) ? 'selected' : '' }}>{{ $display }}</option>
            @endforeach
        </select>
        <small class="form-text text-muted">The Estate's advertisement.</small>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="name">{{ __('lang.advertisementName') }}</label>
    <div class="col-sm-10">
        <input name="name" type="text" class="form-control" placeholder="Name" value="{{ old('name') ?? $advertisement->name ?? '' }}"/>
        <small class="form-text text-muted">The name of advertisement</small>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="en">{{ __('lang.EnName') }}</label>
    <div class="col-sm-10">
        <input name="en" type="text" class="form-control" placeholder="Name" value="{{ old('en') ?? $advertisement->en ?? '' }}"/>
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="ar">{{ __('lang.ArName') }}</label>
    <div class="col-sm-10">
        <input name="ar" type="text" class="form-control" placeholder="Name" value="{{ old('ar') ?? $advertisement->ar ?? '' }}"/>
    </div>
</div>

@csrf

resources/views/dashboard/Advertisement/index.blade.php
@extends('layouts.dashboard')

@section('buttons')
    <a class="btn btn-primary" href="{{route('advertisement.create')}}" role="button">{{ __('lang.addNewAdvertisement') }}</a>
@endsection

@section('content')
    <table class="table">
        <thead>
        <tr>
            <td>Advertisement ID</td>
            <td>Advertisement Name</td>
            <td>Estate Name</td>
            <th class="Actions">{{ __('lang.actions') }}</th>
        </tr>
        </thead>
        <body>
        @foreach($advertisements as $advertisement)
            <tr>
                <td>{{ $advertisement->id }}</td>
                <td>{{ __('advertisement.' . $advertisement->name) }}</td>
                <td>{{ $advertisement->estate->name }}</td>
                <td class="actions">
                    <a
                        href="{{ route('advertisement.edit', ['advertisement' => $advertisement->id]) }}"
                        alt="Edit"
                        title="Edit">
                        {{ __('lang.edit') }}
                    </a>
                    <form action="{{ route('advertisement.destroy', ['advertisement' => $advertisement->id]) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-link" title="Delete" value="Delete">{{ __('lang.delete') }}</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </body>
    </table>
    {{ $advertisements->links() }}
@endsection