routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();

//['verify' => true]

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['middleware' =>['auth' , 'auth.admin'] , 'prefix' => 'dashboard'] , function (){
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::resource('advertisement', 'AdvertisementController');
    Route::resource('EstateType', 'EstateTypeController');
    Route::resource('areas', 'AreaController');
});

Route::get('/verify/{token}' , 'HomeController@verify')->name('verify');

Route::get('/lang/{locale}' , function ($locale){
    session()->put('locale' , $locale);
    return redirect()->back()->withInput();
})->name('language');

app/Http/Controllers/Api/EstateTypeController.php
<?php

namespace App\Http\Controllers\Api;

use App\EstateType;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Resources\EstateType as EstateTypeResource;
class EstateTypeController extends Controller
{
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required',
        ]);

        EstateType::create($validate);

        return response()->json(['message' => 'Added Successfully'] , 200);
    }


    public function show($id)
    {
        $estateType = EstateType::find($id);

        return new EstateTypeResource($estateType);
    }


    public function update(Request $request, $id)
    {
        $estateType =EstateType::findOrFail($id);

        $validate = $request->validate([
            'name' => 'required',
        ]);

        $estateType->update($validate);

        return response()->json(['message' => 'Updated Successfully'] , 200);

    }


    public function destroy($id)
    {
        $estateType =EstateType::findOrFail($id);
        $estateType->delete();

        return response()->json(['message' => 'Deleted Successfully'] , 200);
    }
}

app/Http/Controllers/EstateTypeController.php
<?php

namespace App\Http\Controllers;

use App\EstateType;
use Illuminate\Http\Request;

class EstateTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $estateTypes = EstateType::paginate(5);

        return view('dashboard.EstateType.index' , compact('estateTypes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $estateType = new EstateType();

        return view('dashboard.EstateType.create' , compact('estateType'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validate = $request->validate([
            'name' => 'required',
        ]);

        EstateType::create($validate);

        return redirect(route('EstateType.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $estateType =EstateType::findOrFail($id);

        return view('dashboard.EstateType.edit' , compact('estateType'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $estateType =EstateType::findOrFail($id);

        $validate = $request->validate([
            'name' => 'required',
        ]);

        $estateType->update($validate);

        return redirect(route('EstateType.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $estateType =EstateType::findOrFail($id);
        $estateType->delete();
        return redirect(route('EstateType.index'));
    }
}

resources/views/dashboard/EstateType/create.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="col">
        <form action="{{ route('EstateType.store') }}" method="POST">

            @include('dashboard.EstateType.fields');

            <div class="form-group row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary">{{ __('lang.addEstateType') }}</button>
                </div>
                <div class="col-sm-9">
                    <a href="{{ route('EstateType.index') }}" class="btn btn-secondary">{{ __('lang.cancel') }}</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/EstateType/edit.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="col">
        <form action="{{ route('EstateType.update' , $estateType) }}" method="POST">
            @method('PUT')

            @include('dashboard.EstateType.fields');

            <div class="form-group row">
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-primary">{{ __('lang.addEstateType') }}</button>
                </div>
                <div class="col-sm-9">
                    <a href="{{ route('EstateType.index') }}" class="btn btn-secondary">{{ __('lang.cancel') }}</a>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/dashboard/EstateType/fields.blade.php
@if($errors->any())
    @foreach($errors->all() as $error)
        <p class="alert alert-danger">{{ $error }}</p>
    @endforeach
@endif

<div class="form-group row">
    <label class="col-sm-2 col-form-label" for="name">{{ __('lang.estateTypeName') }}</label>
    <div class="col-sm-10">
        <input name="name" type="text" class="form-control" placeholder="Name" value="{{ old('name') ?? $estateType->name ?? '' }}"/>
        <small class="form-text text-muted">The name of Estate Type</small>
    </div>
</div>

@csrf

resources/views/dashboard/EstateType/index.blade.php
@extends('layouts.dashboard')

@section('buttons')
    <a class="btn btn-primary" href="{{route('EstateType.create')}}" role="button">{{ __('lang.addNewEstateType') }}</a>
@endsection

@section('content')
    <table class="table">
        <thead>
        <tr>
            <td>EstateType ID</td>
            <td>EstateType Name</td>
            <th class="Actions">{{ __('lang.actions') }}</th>
        </tr>
        </thead>
        <body>
        @foreach($estateTypes as $estateType)
            <tr>
                <td>{{ $estateType->id }}</td>
                <td>{{ $estateType->name }}</td>
                <td class="actions">
                    <a
                        href="{{ route('EstateType.edit', ['EstateType' => $estateType->id]) }}"
                        alt="Edit"
                        title="Edit">
                        {{ __('lang.edit') }}
                    </a>
                    <form action="{{ route('EstateType.destroy', ['EstateType' => $estateType->id]) }}" method="POST">
                        @method('DELETE')
                        @csrf
                        <button type="submit" class="btn btn-link" title="Delete" value="Delete">{{ __('lang.delete') }}</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </body>
    </table>
    {{ $estateTypes->links() }}
@endsection